<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HP" ignored="0" name="Test" tests="2" failures="1" timestamp="23 Feb 2018 15:16:30 GMT" time="0.076" errors="0">
  <testcase name="Dummy_test_to_fail" time="0.016" classname="test1.runtestes">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at test1.runtestes.Dummy_test_to_fail(runtestes.java:14)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Dummy_test_to_fail -->
  <testcase name="Dummy_test_to_pass" time="0.001" classname="test1.runtestes"/>
</testsuite> <!-- Test -->
